---
# Remove Telnet if SSH exists on IOSv
- name: Verify SSH enabled
  cisco.ios.ios_command:
    commands:
      - show ip ssh
  register: ssh_status

- name: Verify status
  ansible.builtin.assert:
    that:
      - "'SSH Enabled - version 2.0' in ssh_status.stdout[0]"
    fail_msg: "SSH has not been enabled on {{ inventory_hostname }}"

- name: Remove Telnet
  cisco.ios.ios_command:
    commands:
      - no username {{ ansible_telnet_user }}
      - line vty 0 15
      - transport input ssh
