---
# Configure SSH on IOSv Devices
- name: Check Telnet
  ansible.builtin.wait_for:
    host: "{{ ansible_host }}"
    port: 23
    timeout: 5
    msg: Telnet not open on {{ inventory_hostname }} - {{ ansible_host }}
  register: telnet_check
  ignore_errors: true

- name: Configure SSH
  ansible.netcommon.telnet:
    user: "{{ ansible_ssh_user }}"
    password: "{{ ansible_ssh_pass }}"
    login_prompt: "Username: "
    prompts:
      - "[>#]"
    commands:
      - configure terminal
      - ip domain name {{ domain_name }}
      - crypto key generate rsa modulus 2048
      - ip ssh version 2
      - line vty 0 4
      - transport input telnet ssh
      - username {{ ansible_ssh_user }} privilege 15 secret {{ ansible_ssh_pass }}
  when: not telnet_check.failed

- name: Verify SSH enabled
  cisco.ios.ios_command:
    commands:
      - show ip ssh
  register: ssh_status

- name: Verify status
  ansible.builtin.assert:
    that:
      - "'SSH Enabled - version 2.0' in ssh_status.stdout[0]"
    fail_msg: "SSH has not been enabled on {{ inventory_hostname }}"

- name: Set SSH Only
  cisco.ios.ios_command:
    commands:
      - configure terminal
      - line vty 0 4
      - transport input ssh
