---
# Remove Telnet if SSH exists on IOSv
- name: Configure SSH
  gather_facts: false
  hosts: sites_routing_lab

  tasks:
    - name: Import SSH role
      ansible.builtin.import_role:
        name: ssh

- name: Configure OSPF
  gather_facts: false
  hosts: sites_routing_lab

  tasks:
    - name: Import OSPF role
      ansible.builtin.include_role:
        name: ospf
      when: inventory_hostname in groups['device_roles_edge_router'] or
            inventory_hostname in groups['device_roles_core_switch']
