name: TF and Ansible linting
    
on:
  pull_request:
    types:
      - opened
      - reopened
    branches:
      - main
  push:
    branches: 
      - main

permissions: read-all

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    
# Checkout Repository
    - name : Check out Git Repository
      uses: actions/checkout@v4
      
# TFLint - Setup Teraform
    - uses: terraform-linters/setup-tflint@v4
      name: Setup TFLint
      with:
        github_token: ${{ secrets.CI_GITHUB_TOKEN }}
        
# Print TFLint version
    - name: Show version
      run: tflint --version
      
# Run tflint command in each directory recursively
    - name: Run TFLint
      run: tflint -f compact --recursive 

# Runs ansible-lint
    - name: Run ansible-lint
      uses: ansible/ansible-lint@v24.7.0
